name: Publish Docker Image

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Tags
        id: meta
        run: |
          tags="ghcr.io/${{ github.repository }}:latest"
          if [[ $(date '+%d') == 01 || "${{ github.event_name }}" == "push" ]]; then
            tags="${tags},ghcr.io/${{ github.repository }}:$(date '+%Y-%m-%d')"
          fi
          echo "tags=${tags}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
